name: Build

on:
  push:
    branches: [ workflow-5.15.16 ]

jobs:
  build:
    runs-on: windows-latest

    env:
      SET_VC_VARS: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64
      QTVER: 5.15.16
      PREFIX: ${{ github.workspace }}\Qt

    defaults:
      run:
        shell: cmd

    steps:
      # - name: Checkout Repository
      #   uses: actions/checkout@v4
      #   with:
      #     ref: workflow-5.15.16
      # - name: Download Sources
      #   run: |
      #     call "%SET_VC_VARS%"
      #     cd "${{ github.event.repository.name }}"
      #     call qt download
      # - name: Build OpenSSL
      #   run: |
      #     call "%SET_VC_VARS%"
      #     cd "${{ github.event.repository.name }}"
      #     call qt openssl
      # - name: Configure Qt Build
      #   run: |
      #     call "%SET_VC_VARS%"
      #     cd "${{ github.event.repository.name }}"
      #     call qt setup
      # - name: Build and Install Qt
      #   run: |
      #     call "%SET_VC_VARS%"
      #     cd "${{ github.event.repository.name }}"
      #     call qt build
      - name: 7z Compress
        id: zip
        run: |
          echo "zip-file-name=abc123" >> "%GITHUB_OUTPUT%"
          echo ${{ steps.zip.outputs.zip-file-name }}
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.zip.outputs.zip-file-name }}
          tag_name: qt%QTVER%
          body: 'Statically linked Qt%QTVER%'
          target_commitish: workflow-5.15.16